{% set name = "py-cpuinfo" %}
{% set version = "8.0.0" %}
{% set sha256 = "5f269be0e08e33fd959de96b34cd4aeeeacac014dd8305f70eb28d06de2345c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - cpuinfo = cpuinfo:main

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - cpuinfo
  commands:
    - cpuinfo

about:
  home: https://github.com/workhorsy/py-cpuinfo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A module for getting CPU info with Python 2 & 3
  dev_url: https://github.com/workhorsy/py-cpuinfo

extra:
  recipe-maintainers:
    - mstimberg
